version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: proyectoBDD2
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
      - "4200:4200"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: proyectoBDD2
      MYSQL_PORT: 3306
    links:
      - mysql

volumes:
  mysql-data:
